apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopetshop-production
  annotations:
    argo.octopus.com/project: "octopetshop"
    argo.octopus.com/environment: "production"
spec:
  project: default
  source:
     repoURL: https://github.com/OctopusDeploy/samples-argo-cd-gitops.git
     targetRevision: HEAD
     path: octopetshop/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true