apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: update-image-tags-helm-octopub-test
  annotations:
    argo.octopus.com/project.no-git-creds: "update-image-tags-helm"
    argo.octopus.com/project: "update-image-tags-helm"
    argo.octopus.com/environment: "test"
    argo.octopus.com/environment.third: test
    argo.octopus.com/environment.values-source: test
    argo.octopus.com/image-replace-paths.helm-source: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
    argo.octopus.com/project.the-ref: update-image-tags-helm
spec:
  project: default
  sources:
    - repoURL: https://github.com/OctopusDeployTesting/frank-samples-argo-cd-gitops
      targetRevision: HEAD
      name: helm-source
      path: manifests/update-image-tags-helm-octopub/test/chart
      helm:
        valueFiles:
          - $values/manifests/update-image-tags-helm-octopub/test/values/values.yaml
    - repoURL: https://github.com/OctopusDeployTesting/frank-samples-argo-cd-gitops
      targetRevision: HEAD
      ref: values
      name: values-source
    - repoURL: https://github.com/OctopusDeployTesting/frank-samples-argo-cd-gitops
      targetRevision: HEAD
      path: manifests/update-image-tags-helm-octopub/test/values
    - path: manifests/update-image-tags-helm-octopub/test/values
      repoURL: https://github.com/OctopusSolutionsEngineering/samples-argo-cd-gitops
      targetRevision: HEAD
      name: no-git-creds
  destination:
    server: https://kubernetes.default.svc
    namespace: update-image-tags-helm-octopub-test
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
